// Generated by Rcpp::compileAttributes() -- do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// find_optimal_tau_cpp
List find_optimal_tau_cpp(NumericMatrix predictions_low, NumericMatrix predictions_high, NumericVector tau_grid, double alpha);
RcppExport SEXP _optCQR_find_optimal_tau_cpp(SEXP predictions_lowSEXP, SEXP predictions_highSEXP, SEXP tau_gridSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type predictions_low(predictions_lowSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type predictions_high(predictions_highSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau_grid(tau_gridSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(find_optimal_tau_cpp(predictions_low, predictions_high, tau_grid, alpha));
    return rcpp_result_gen;
END_RCPP
}
// compute_conformity_scores_cpp
NumericVector compute_conformity_scores_cpp(NumericMatrix predictions_low, NumericMatrix predictions_high, NumericVector Y, IntegerVector optimal_indices);
RcppExport SEXP _optCQR_compute_conformity_scores_cpp(SEXP predictions_lowSEXP, SEXP predictions_highSEXP, SEXP YSEXP, SEXP optimal_indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type predictions_low(predictions_lowSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type predictions_high(predictions_highSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type optimal_indices(optimal_indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_conformity_scores_cpp(predictions_low, predictions_high, Y, optimal_indices));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_optCQR_find_optimal_tau_cpp", (DL_FUNC) &_optCQR_find_optimal_tau_cpp, 4},
    {"_optCQR_compute_conformity_scores_cpp", (DL_FUNC) &_optCQR_compute_conformity_scores_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_optCQR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
