# Generated by Rcpp::compileAttributes() -- do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib optCQR, .registration = TRUE
#' @importFrom Rcpp sourceCpp
NULL

#' Find Optimal Tau Values via C++ Optimization
#'
#' For each observation, finds the tau value that minimizes the prediction
#' interval length while maintaining the specified coverage width (1-alpha).
#'
#' @param predictions_low Matrix of lower quantile predictions (n x n_tau)
#' @param predictions_high Matrix of upper quantile predictions (n x n_tau)
#' @param tau_grid Vector of candidate tau values
#' @param alpha Miscoverage level
#'
#' @return A list with optimal_tau, min_lengths, and optimal_indices
#'
#' @keywords internal
find_optimal_tau_cpp <- function(predictions_low, predictions_high, tau_grid, alpha) {
    .Call(`_optCQR_find_optimal_tau_cpp`, predictions_low, predictions_high, tau_grid, alpha)
}

#' Compute Conformity Scores
#'
#' Computes conformity scores E_i = max(q_low - Y, Y - q_high, 0) for each
#' observation using the optimal tau indices.
#'
#' @param predictions_low Matrix of lower quantile predictions
#' @param predictions_high Matrix of upper quantile predictions
#' @param Y Vector of true response values
#' @param optimal_indices Vector of optimal tau indices (0-based)
#'
#' @return Vector of conformity scores
#'
#' @keywords internal
compute_conformity_scores_cpp <- function(predictions_low, predictions_high, Y, optimal_indices) {
    .Call(`_optCQR_compute_conformity_scores_cpp`, predictions_low, predictions_high, Y, optimal_indices)
}
